### ISSUE TITLE
Strategy for generating cohort ID (accession)

### ISSUE THREAD

**Issue by theisuru** [EBIBioSamples/cohort-atlas#1]
We need to issue an accession to registering cohorts. We will issue an accession number similar to ENA. 
eg. BSC000001 (BSC - BioSample Cohort)
- There will be multiple instances of the application running, accession should be safely generated (use DB features?)

**Comment by snathanvj** [comment]
**My proposal:**
  Accession format: 3 letter constant BSC + 2 letter combination(e., AB) + 6 digits to start

**Details:**

**BSCAB000001**

1) create DB sequence increment by 1 every time
construct 6 digits, i.e first time it will be
000001
2) create prefix constant table 

perfix table:

 AB ACTIVE
 AC   
 AD
 AE
 AF
 AG
 AH
 AI
 AJ
 AK

3) slect prefix from prefix where state='ACTIVE'
if number > 999999 reset sequence to 1 and move prefix to next (either sort them aplhabeticaly or have an auto increment, doesn't really matter)


 AB NA
 AC ACTIVE  
 AD
 AE
 AF
 AG
 AH
 AI
 AJ
 AK

 Finally we will get BSC+ 2 alpha prefix + 6 numeric accession
 e.g., BSCAB000001


 This approach is much simpler and we won't run out of accession easily(probably never)

 27! * 999999 accession we will be having, even if we run out we can increase the numbers.

**Comment by theisuru** [comment]
Sounds good, but wouldn't it be much simpler if we select a prefix say "BSC" and then append the numeric portion. We will add a 6 digits number if it overflows, it is going to be 7 digits. (I don't think it will overflow :))
